services:
  catalogdb:
    container_name: catalogdb
    image: mongo

  basketdb:
    container_name: basket.api
    image: redis:alpine

  discountdb:
    container_name: discountdb
    image: postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4

  portainer:
    container_name: portainer
    image: portainer/portainer-ce

  catalog.api:
    container_name: catalog.api
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile



  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
  
  

