services:
 catalogdb:
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
 catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionSetting:ConnectionString=mongodb://CatalogDb:27017"
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on: 
      - catalogdb
    ports:
      - "8080"
