services:
  catalogdb:
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  basketdb:
    restart: always
    ports: 
      - "6379:6379"

  discountdb:
    restart: always
    ports: 
      - "5432:5432"
    entrypoint:
     - "POSTGRES_USER=admin"
     - "POSTGRES_PASSWORD=admin1234"
     - "POSTGRES_DB=DiscountDb"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  portainer:
    restart: always
    ports: 
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data 

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionSetting:ConnectionString=mongodb://catalogdb:27017"
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on: 
      - catalogdb
    ports:
      - "8080:8080"

  pgadmin:
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin


  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSetting:ConnectionString=basketdb:6379"
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on: 
     - basketdb


volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:



